### ISSUE TITLE
help to install and use .

### ISSUE THREAD

**Issue by ingnelson** [vejryn/auto-journal#1]
Hi.
i am trying to use your project , could you create a mini tutorial on readme , please ?.

1) on main.py file i changed on line 9 `_setting` for `setting`
2) i installed the modules `pip install gspread` and `pip install --upgrade oauth2client`
3) i have the next essue : 

```
  $ python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    creds = ServiceAccountCredentials.from_json_keyfile_name('_secret.json', sco
pe)
  File "C:\Users\casa\AppData\Local\Programs\Python\Python38\lib\site-packages\o
auth2client\service_account.py", line 219, in from_json_keyfile_name
    with open(filename, 'r') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '_secret.json'

```

How to solve that problem ? i hope you reply this message.

**Comment by vejryn** [comment]
Hello Nelson, sure! I will update the readme, tutorials to setup google api credentials, and fix things up. _secret.json files supposedly consist of google api credentials. I'm currently working on it.

**Comment by ingnelson** [comment]
Thank for your reply , I am going to wait your update. 
Thank you very much .

**Comment by vejryn** [comment]
Hello @ingnelson, I've updated few things on main.py, and for the credentials and sharing setting I've already made a new README directory you can check here:

https://github.com/vejryn/auto-journal/tree/master/README

if you prefer video over picture for the tutorials, I initially watch this youtube video even though it's not specifically for this journal, I think it can help you : https://www.youtube.com/watch?v=cnPlKLEGR7E
